name: publish

on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 
        uses: actions/checkout@v4
        with:
          dotnet-version: '6.0.0'
          
      - name: Restore
        run: dotnet restore .TaskManagementBlazor.sln
      - name: Build
        run: dotnet build .TaskManagementBlazor.sln
      
